# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 00:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='visibility_status',
            field=models.IntegerField(choices=[(1, 'Public'), (2, 'Team'), (3, 'Private')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='case_status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Assigned'), (3, 'Processing'), (4, 'Closed'), (5, 'KIV')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='visibility_status',
            field=models.IntegerField(choices=[(1, 'Public'), (2, 'Team'), (3, 'Private')]),
        ),
    ]
